### ISSUE TITLE
Screen goes blank before firmware selection

### ISSUE THREAD

**Issue by eikotehmouse** [400plus/400plus#455] opened 2022-10-02 23:17 UTC
clean formatted card. with latest testfir.fir on card. I go into update firmware and as it says "loading..." to bring up the firmware selection. I just get a blank screen. Is this part of it or is there something wrong? it doesn't power off when i turn the switch off. Nothing takes when I continue the proccess after waiting 5 mins. And doing the rest of the install instructions

**Comment by eikotehmouse** [comment] 2022-10-03 00:17
I think I got something to work on the card. But all I get is a black screen and cant turn off camera once turned on. Boots normally without a card

**Comment by 0xAF** [comment] 2022-10-03 00:22
This is expected IIRC. It should be explained somewhere in the instructions.
Once the testfir finish you should expect black screen and you cannot power off. You should pull out the battery.
Please read the docs, This is not a bug and we cannot fix this.
Once the testfir step is done, you should remove testfir file and proceed with the autoexec.bin file.

I will close this issue.
Please reopen if you think there is more to discuss.

**Closed as completed by 0xAF** 2022-10-03 00:22 UTC

**Comment by eikotehmouse** [comment] 2022-10-03 04:19
let me re word my second comment.

After I did everything. All the way up to loading 400PLUS folder with the required file and putting it back in and starting up the camera. All I get is a black screen and can't turn off my camera. It still can focus when on. But that is about it.

secondly, the instructions do not state that the screen will go blank before the firmware selection loads. I was only assuming something wrong was happening.


NVM figured it out my self... its 2022... a YT video would be really great. I notice a few more issues now that i got to mess with it but, ill put that in another thread

**Comment by 0xAF** [comment] 2022-10-03 12:42
I agree it's not quite clear what to expect, but still, the 4th step in the [instructions](https://github.com/400plus/400plus/wiki/Firmware-Hack-Installation) is:

> ...  the screen will go blank. Wait at least 2 minutes, then turn it off, and finally take battery out and back in.

As for the problem with the hack itself. Have you [prepared](https://github.com/400plus/400plus/wiki/Firmware-Hack-Installation#preparing-each-card) the card?
Does the [blue light blink](https://github.com/400plus/400plus/wiki/Firmware-Hack-Installation#testing-400plus) when starting the camera?
Have you tried to [start the camera with the hack disabled](https://github.com/400plus/400plus/wiki/Firmware-Hack-Installation#temporarily-disable-400plus), by holding the TRASH button while powering on? Does it start?

>   its 2022... a YT video would be really great.

I agree, but this project is not active anymore. Last commit in the repository is 5 years old. The developers moved on other projects. If you have the will, you can create a video with instructions, I will put it in the instructions.

**Comment by eduperez** [comment] 2022-10-04 09:21
Looks like the camera ha been prepared, and it is looking for 400plus on the card, but cannot find it; redo all the steps explained at "preparing each card", and try again.
